### ISSUE TITLE
Guardian precision collapse: 10 findings on #278, skeptic-confirmed 10/10, none real (one would break the build)

### ISSUE THREAD

**Issue by zaebee** [zaebee/codegraph-brain#279]
## Guardian reviewed its own fix and produced 10 findings, 0 of them real

`/guardian review` on #278 ([run 30579616824](https://github.com/zaebee/codegraph-brain/actions/runs/30579616824)) returned **10 findings**, all of which the skeptic confirmed — `skeptic_status: ok`, `skeptic 10/10`. Every one was checked by hand or by execution. **None is a real defect, and one would break the build if applied.**

This is the opposite failure mode from #246 / #270, where the finder's problem was precision *bias* — staying silent. Here precision collapsed, and the skeptic, which exists precisely to catch that, rubber-stamped everything.

### The dangerous one

> `base.py:102` 🟡 **Unreachable code after loop in `_retry`** — "The loop either returns or raises on the last attempt, making this line unreachable… Fix: Remove the unreachable `raise AssertionError` line."

Removing it fails the build:

```
src/cgis/guardian/providers/base.py:73: error: Missing return statement  [return]
```

mypy cannot prove the `for` loop always returns or raises, so the trailing `raise` is **required**, not dead. The finding's own justification ("violates mypy strict's unreachable check") is backwards — mypy strict passes *with* the line and fails *without* it. Verified by deleting it and running `uv run mypy src`.

### The other nine

| # | file | claim | verdict |
|---|---|---|---|
| 1 | `base.py:7` | `RETRYABLE_EXCEPTIONS` lacks type annotations, mypy may see `Any` | **False.** Annotated `tuple[type[Exception], ...]`; mypy strict passes on 66 files |
| 3 | `base.py:69` | `_sleep` may receive a negative `seconds` | Speculative; no caller can produce one (`BACKOFF_BASE ** attempt`), no scenario given |
| 4 | `mistral.py:26` | integer overflow in `timeout * 1000` | **False.** Python ints are arbitrary precision |
| 5 | `gemini.py:25` | same overflow claim | **False**, and a duplicate of #4 |
| 6 | `base.py:84` | tuple "may miss httpx subclasses… e.g. ConnectTimeout, ReadTimeout" | **False, and self-contradicting** — it names exceptions that *are* covered |
| 7 | `runner.py:217` | rounding `duration_s` to 2 dp loses sub-millisecond precision | 10 ms resolution on a 65 s measurement |
| 8 | `metrics.py:68` | no runtime validation that `duration_s` is float-or-None | No field in `metrics.py` has runtime validation; it is a plain dict → JSON |
| 9 | `test_..._providers.py:62` | asserting exactly 3 calls is brittle | Cosmetic at most |
| 10 | `test_..._providers.py:71` | "assumes MAX_ATTEMPTS calls… could be misleading" | **Premise false** — that test already derives its expectation from `MAX_ATTEMPTS` |

Finding 6 verified by execution — every relevant httpx transport exception is caught by the two-entry tuple:

```
ReadTimeout True   ConnectTimeout True   WriteTimeout True   PoolTimeout True
ConnectError True  ReadError True        WriteError True     CloseError True
```

### Why this is worth a ticket rather than a shrug

The report *reads* authoritative. Each false finding carries a severity chip and a `_Verified by codestral-latest_` footer. A reviewer who trusts the badge and applies finding 2 breaks `make type-check`.

Two properties of this diff may be what broke it, both worth testing rather than assuming:

- **It is infrastructure code**, not business logic — retry loops, exception tuples, unit conversions. The finder appears to pattern-match on shapes that *look* risky (a bare `raise`, an int multiplication, a broad `except`) without checking whether the risk is realizable in Python or in this codebase.
- **The skeptic shares the failure.** 10/10 confirmed. Whatever it is judging, it is not "can this actually happen here".

### Concrete next step: this PR is a ready-made precision benchmark

`benchmarks/guardian/` already has the exact pattern — from `CURATION.md`, PR 141:

> ALL findings → ambiguous (style/maintainability only; guardian precision rules forbid)
> GT findings: NONE → recall vacuously 1.0; PR measures noise on a clean-ish PR.

`GroundTruth.findings` accepts an empty list, so #278 slots straight in — and it is a **harder** precision test than anything currently in the set, because these findings are not merely stylistic-ambiguous, they are refuted by execution.

```yaml
# PR 278 — fix(guardian): explicit request timeout + bounded retry. See CURATION.md.
# Guardian produced 10 findings, skeptic-confirmed 10/10, ALL refuted.
# GT findings: NONE → this PR measures precision/noise only.
pr: 278
base: 2e768cef585f10481970697657b0a9b40a411f47
head: 6ee175e553c784a363c190e00021be5d365fb8dd
findings: []
```

With that in place, `scripts/guardian_bench.py` gives a regression number for any future prompt or skeptic change: **10 false positives is the current baseline, and it should go down.**

Related: #246, #270 (skeptic judgement + impact scoring), #275 (the PR under review).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by zaebee** [comment]
## Acceptance criterion 3 — verified in production

The `/guardian review` run on PR #281 ([run 30589024612](https://github.com/zaebee/codegraph-brain/actions/runs/30589024612)) is the first with the recording step live on `main`. It produced both artifacts:

```
guardian-finder-281  — 10,321 bytes
guardian-metrics-281 —  1,753 bytes
```

Downloaded and loaded it:

```
ПАРСИТСЯ. diff: 30,177 chars | findings: 6
verdicts after load: {None} | skeptic_status: off
```

So the full contract holds end to end: the artifact exists, `load_finder_recording` parses it, and the skeptic's marks are stripped on read so a replay starts from unjudged findings. **Criterion 3 closed.**

Worth noting what this immediately bought. For #278 the baseline had to be assembled by hand from rendered PR comments, which drop `evidence` and `confidence` — a faithful recording could not be reconstructed at all. For #281 the actual finder output was available, with per-finding confidence:

```
src/cgis/guardian/chunker.py:42   conf=70  Filtering logic may incorrectly handle paths with multiple dots
src/cgis/guardian/chunked.py:153  conf=60  Double-parsing of diff text for empty check
src/cgis/guardian/chunker.py:32   conf=50  Default parameter type could be more precise
tests/unit/test_guardian_chunker.py:340 conf=50  Test does not cover edge case of empty reviewable_suffixes
tests/unit/test_guardian_chunker.py:330 conf=40  Test does not verify chunk content beyond file list
src/cgis/guardian/chunked.py:110  conf=0   Missing type annotation for return value of _single_pass
```

That is exactly the artifact the precision benchmark needs, and it is now produced by every run at no extra cost.

## Third precision datapoint

| PR | findings | held up |
|----|----------|---------|
| #278 | 10 | **0** |
| #280 | 11 | 2 |
| #281 | 6 | 1 |

On #281 the one that held was the untested `reviewable_suffixes=()` edge — a real, if small, coverage gap, now pinned by a test. Of the other five: the highest-confidence claim (multi-dot paths, conf 70) is refuted by execution — `a.b.py` and `src/mod.test.py` are kept, `x.pyc` and `weird.py.bak` dropped, all correct; the double-parse is a tradeoff argued explicitly in that PR's spec; and the conf=0 finding claims a missing return annotation on a function annotated `-> RoutedReview`.

Two things the confidence numbers suggest, now that they are visible: the model scored its own clearly-false finding at **0**, and this run's maximum confidence (70) is well below the earlier runs' — so the signal may carry information worth using in the benchmark rather than treating all findings as equal.

Not drawing conclusions from three points. That is what `benchmarks/guardian/pr-278.yaml` and the recordings are for.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
